/* ==========================================================================
   github.js — automatic project discovery
   --------------------------------------------------------------------------
   Architecture (hybrid, chosen for reliability + true auto-discovery):

     1. Load data/projects.json — generated by a GitHub Actions workflow.
        Instant, no rate limit, works even if the GitHub API is unreachable.
     2. In the background, query the public GitHub REST API. If it answers,
        re-render with live data so a repository created minutes ago appears
        without waiting for the next workflow run.
     3. If both fail, show a professional fallback — never a broken section.

   No tokens. No backend. Public repository data only.
   ========================================================================== */
(function () {
  "use strict";

  var CFG   = window.SITE_CONFIG || {};
  var PCFG  = window.PROJECT_CONFIG || {};
  var RULES = window.DOMAIN_RULES || [];
  var U     = window.PortfolioUtils;

  var resultsEl  = document.getElementById("projectResults");
  var filtersEl  = document.getElementById("projectFilters");
  var countEl    = document.getElementById("projectCount");
  var statusEl   = document.getElementById("projectStatus");
  var footerEl   = document.getElementById("projectFooterActions");

  if (!resultsEl) return;

  var state = {
    projects: [],
    source: null,        // "snapshot" | "live"
    generatedAt: null,
    activeFilter: "all",
    showAll: !!PCFG.showUnclassified,
    rendered: false
  };

  var PROFILE_URL = U.githubProfileUrl();

  /* ======================================================================
     Classification
     ====================================================================== */
  function lower(list) {
    return (list || []).map(function (t) { return String(t).toLowerCase(); });
  }

  function hasAny(topics, candidates) {
    for (var i = 0; i < topics.length; i++) {
      if (candidates.indexOf(topics[i]) !== -1) return true;
    }
    return false;
  }

  function resolveDomain(topics, language, text) {
    for (var i = 0; i < RULES.length; i++) {
      if (hasAny(topics, RULES[i].match)) return RULES[i].label;
    }
    // Weak fallback from the description text.
    if (/\buav|drone|quadcopter|flight\b/.test(text)) return "UAV / UAS";
    if (/\bcontrol|pid|kalman|observer|stability\b/.test(text)) return "Control Systems";
    if (/\bembedded|firmware|microcontroller|stm32|arduino\b/.test(text)) return "Embedded Systems";
    if (/\bsimulat|model\b/.test(text)) return "Modeling & Simulation";
    if (language) return "Computational Engineering";
    return "Engineering";
  }

  function classify(repo) {
    var topics   = lower(repo.topics);
    var name     = String(repo.name || "").toLowerCase();
    var desc     = String(repo.description || "").toLowerCase();
    var text     = name.replace(/[-_]/g, " ") + " " + desc;
    var language = repo.language || "";

    var isFeatured  = topics.indexOf(String(PCFG.featuredTopic || "").toLowerCase()) !== -1;
    var isPortfolio = hasAny(topics, lower(PCFG.portfolioTopics));
    var isEngTopic  = hasAny(topics, lower(PCFG.engineeringTopics));

    var keywordHit = false;
    var keywords = lower(PCFG.engineeringKeywords);
    for (var i = 0; i < keywords.length; i++) {
      if (text.indexOf(keywords[i]) !== -1) { keywordHit = true; break; }
    }

    var tier;
    if (isFeatured)                                tier = "featured";
    else if (isPortfolio || isEngTopic)            tier = "engineering";
    else if (keywordHit && (desc || topics.length)) tier = "engineering";
    else                                            tier = "other";

    /* Ranking score. Deliberately simple and explainable:
       intent signals dominate, then evidence of care, then recency. */
    var score = 0;
    if (isFeatured)  score += 1000;
    if (isPortfolio) score += 300;
    if (isEngTopic)  score += 200;
    if (keywordHit)  score += 60;
    score += Math.min(topics.length, 8) * 12;      // topics = curated repo
    if (repo.description) score += 40;
    if (repo.homepage)    score += 15;
    if (repo.has_pages)   score += 10;
    score += Math.min(repo.stargazers_count || 0, 50) * 2;

    var updated = Date.parse(repo.pushed_at || repo.updated_at || 0) || 0;
    var daysOld = (Date.now() - updated) / 86400000;
    if (updated) score += Math.max(0, 90 - daysOld) / 3;   // gentle recency nudge

    return {
      tier: tier,
      score: score,
      domain: resolveDomain(topics, language, text)
    };
  }

  function normalise(repo) {
    var meta = classify(repo);
    return {
      name: repo.name,
      fullName: repo.full_name || (CFG.githubUsername + "/" + repo.name),
      description: repo.description || "",
      url: repo.html_url || ("https://github.com/" + CFG.githubUsername + "/" + repo.name),
      homepage: repo.homepage || "",
      language: repo.language || "",
      topics: (repo.topics || []).slice(0, 8),
      updatedAt: repo.pushed_at || repo.updated_at || "",
      stars: repo.stargazers_count || 0,
      archived: !!repo.archived,
      fork: !!repo.fork,
      tier: meta.tier,
      score: meta.score,
      domain: meta.domain
    };
  }

  function shouldExclude(repo) {
    var name = String(repo.name || "").toLowerCase();
    var excluded = lower(PCFG.excludeRepos).concat([
      String(CFG.repoName || "").toLowerCase(),
      String(CFG.githubUsername || "").toLowerCase(),
      ".github"
    ]);
    if (excluded.indexOf(name) !== -1) return true;
    if (repo.private) return true;
    if (PCFG.hideForks && repo.fork) return true;
    if (PCFG.hideArchived && repo.archived) return true;
    return false;
  }

  function prepare(repos) {
    if (!Array.isArray(repos)) return [];
    return repos
      .filter(function (r) { return r && r.name && !shouldExclude(r); })
      .map(normalise)
      .sort(function (a, b) { return b.score - a.score; });
  }

  /* ======================================================================
     Data sources
     ====================================================================== */
  function loadSnapshot() {
    if (!window.fetch) return Promise.reject(new Error("fetch unsupported"));
    return fetch("data/projects.json", { cache: "no-cache" })
      .then(function (res) {
        if (!res.ok) throw new Error("snapshot " + res.status);
        return res.json();
      })
      .then(function (payload) {
        var repos = Array.isArray(payload) ? payload : (payload.repositories || []);
        if (!repos.length) throw new Error("snapshot empty");
        return { repos: repos, generatedAt: payload.generatedAt || null };
      });
  }

  function loadLive() {
    if (!window.fetch) return Promise.reject(new Error("fetch unsupported"));
    var user = CFG.githubUsername;
    if (!user || /^your_github_username$/i.test(user)) {
      return Promise.reject(new Error("username not configured"));
    }
    var url = "https://api.github.com/users/" + encodeURIComponent(user) +
              "/repos?per_page=" + (PCFG.perPage || 100) + "&sort=updated&type=owner";

    return fetch(url, { headers: { Accept: "application/vnd.github+json" } })
      .then(function (res) {
        if (res.status === 403 || res.status === 429) throw new Error("rate-limited");
        if (res.status === 404) throw new Error("user-not-found");
        if (!res.ok) throw new Error("api " + res.status);
        return res.json();
      })
      .then(function (repos) {
        if (!Array.isArray(repos)) throw new Error("malformed response");
        return repos;
      });
  }

  /* ======================================================================
     Rendering
     ====================================================================== */
  var esc = U.escapeHtml;

  function visibleProjects() {
    return state.projects.filter(function (p) {
      if (p.tier === "other" && !state.showAll) return false;
      if (state.activeFilter === "all") return true;
      if (state.activeFilter === "featured") return p.tier === "featured";
      return p.domain === state.activeFilter;
    });
  }

  function cardMarkup(p) {
    var isFeatured = p.tier === "featured";
    var detailUrl  = "projects/?repo=" + encodeURIComponent(p.name);

    var badges = [];
    if (isFeatured) badges.push('<span class="pill pill--featured">Featured</span>');
    else if (p.tier === "other") badges.push('<span class="pill">Repository</span>');
    if (p.archived) badges.push('<span class="pill">Archived</span>');

    var topics = p.topics.length
      ? '<div class="tag-row project-card__topics">' +
          p.topics.map(function (t) { return '<span class="tag">' + esc(t) + "</span>"; }).join("") +
        "</div>"
      : "";

    var desc = p.description
      ? '<p class="project-card__desc">' + esc(p.description) + "</p>"
      : '<p class="project-card__desc is-empty">No repository description provided.</p>';

    return '' +
      '<article class="project-card' + (isFeatured ? " project-card--featured" : "") + '">' +
        '<div class="project-card__top">' +
          '<span class="pill' + (isFeatured ? " pill--featured" : "") + '">' + esc(p.domain) + "</span>" +
          (badges.length > 1 || (badges.length === 1 && !isFeatured) ? badges.slice(isFeatured ? 1 : 0).join("") : "") +
        "</div>" +
        '<h3 class="project-card__title"><a href="' + esc(p.url) + '" target="_blank" rel="noopener noreferrer">' +
          esc(p.name) + "</a></h3>" +
        desc +
        '<dl class="project-card__meta">' +
          "<div><dt>Domain</dt><dd>" + esc(p.domain) + "</dd></div>" +
          "<div><dt>Language</dt><dd>" +
            (p.language ? '<span class="lang-dot" aria-hidden="true"></span>' + esc(p.language) : "Not specified") +
          "</dd></div>" +
          "<div><dt>Updated</dt><dd>" + esc(U.formatDate(p.updatedAt)) + "</dd></div>" +
        "</dl>" +
        topics +
        '<div class="project-card__actions">' +
          '<a class="btn btn--solid btn--sm" href="' + esc(p.url) + '" target="_blank" rel="noopener noreferrer">View Repository</a>' +
          '<a class="btn btn--outline btn--sm" href="' + esc(detailUrl) + '">View Details</a>' +
          (p.homepage ? '<a class="btn btn--outline btn--sm" href="' + esc(p.homepage) + '" target="_blank" rel="noopener noreferrer">Live</a>' : "") +
        "</div>" +
      "</article>";
  }

  function renderFilters() {
    if (!filtersEl) return;
    var domains = {};
    state.projects.forEach(function (p) {
      if (p.tier === "other" && !state.showAll) return;
      domains[p.domain] = (domains[p.domain] || 0) + 1;
    });

    var buttons = ['<button type="button" class="filter-btn" data-filter="all">All</button>'];
    if (state.projects.some(function (p) { return p.tier === "featured"; })) {
      buttons.push('<button type="button" class="filter-btn" data-filter="featured">Featured</button>');
    }
    Object.keys(domains).sort().forEach(function (d) {
      buttons.push('<button type="button" class="filter-btn" data-filter="' + esc(d) + '">' +
        esc(d) + " (" + domains[d] + ")</button>");
    });

    filtersEl.innerHTML = buttons.join("");
    filtersEl.querySelectorAll(".filter-btn").forEach(function (btn) {
      var isActive = btn.getAttribute("data-filter") === state.activeFilter;
      btn.setAttribute("aria-pressed", isActive ? "true" : "false");
      btn.addEventListener("click", function () {
        state.activeFilter = btn.getAttribute("data-filter");
        renderFilters();
        renderList();
      });
    });
  }

  function renderFooter() {
    if (!footerEl) return;
    var hiddenCount = state.projects.filter(function (p) { return p.tier === "other"; }).length;
    var parts = ['<a class="btn btn--outline" href="' + PROFILE_URL +
      '" target="_blank" rel="noopener noreferrer">All repositories on GitHub</a>'];

    if (hiddenCount) {
      parts.push('<button type="button" class="btn btn--outline" id="toggleAllRepos">' +
        (state.showAll ? "Show engineering projects only" : "Show all repositories (" + hiddenCount + " more)") +
        "</button>");
    }

    footerEl.innerHTML = parts.join("");
    var toggleBtn = document.getElementById("toggleAllRepos");
    if (toggleBtn) {
      toggleBtn.addEventListener("click", function () {
        state.showAll = !state.showAll;
        state.activeFilter = "all";
        renderFilters();
        renderList();
        renderFooter();
      });
    }
  }

  function renderList() {
    var items = visibleProjects();

    if (!items.length) {
      resultsEl.innerHTML =
        '<div class="state">' +
          "<h3>No matching projects</h3>" +
          "<p>No public repository matches this filter yet. Repositories tagged with engineering " +
          "topics on GitHub appear here automatically.</p>" +
          '<div class="btn-row" style="justify-content:center;margin-top:1rem">' +
            '<a class="btn btn--outline btn--sm" href="' + PROFILE_URL +
              '" target="_blank" rel="noopener noreferrer">Open GitHub profile</a>' +
          "</div>" +
        "</div>";
    } else {
      resultsEl.innerHTML = '<div class="project-grid">' + items.map(cardMarkup).join("") + "</div>";
    }

    if (countEl) {
      var total = state.projects.filter(function (p) {
        return state.showAll ? true : p.tier !== "other";
      }).length;
      var suffix = state.source === "live"
        ? "live from GitHub"
        : ("synced " + (state.generatedAt ? U.formatDate(state.generatedAt) : "from repository data"));
      countEl.textContent = items.length + " of " + total + " shown · " + suffix;
    }

    if (statusEl) {
      statusEl.textContent = items.length + " projects loaded.";
    }
    state.rendered = true;
  }

  function renderAll(repos, source, generatedAt) {
    var prepared = prepare(repos);
    if (!prepared.length) {
      if (!state.rendered) renderEmpty();
      return;
    }
    state.projects = prepared;
    state.source = source;
    state.generatedAt = generatedAt || null;
    renderFilters();
    renderList();
    renderFooter();
  }

  function renderEmpty() {
    if (filtersEl) filtersEl.innerHTML = "";
    if (countEl) countEl.textContent = "";
    resultsEl.innerHTML =
      '<div class="state">' +
        "<h3>No public engineering repositories yet</h3>" +
        "<p>Public repositories tagged with engineering topics will be listed here automatically as " +
        "they are published.</p>" +
        '<div class="btn-row" style="justify-content:center;margin-top:1rem">' +
          '<a class="btn btn--outline btn--sm" href="' + PROFILE_URL +
            '" target="_blank" rel="noopener noreferrer">Open GitHub profile</a>' +
        "</div>" +
      "</div>";
    if (statusEl) statusEl.textContent = "No projects available.";
  }

  function renderError(reason) {
    if (filtersEl) filtersEl.innerHTML = "";
    if (countEl) countEl.textContent = "";

    var detail = "Project repositories are temporarily unavailable. Please visit GitHub directly to " +
                 "view the latest engineering work.";
    if (reason === "rate-limited") {
      detail = "GitHub's public API rate limit has been reached from this network. The project list " +
               "will load again shortly — in the meantime, the repositories are available on GitHub.";
    } else if (reason === "user-not-found") {
      detail = "The configured GitHub account could not be found. Check githubUsername in js/config.js.";
    } else if (reason === "username not configured") {
      detail = "The GitHub username has not been configured yet. Set githubUsername in js/config.js.";
    }

    resultsEl.innerHTML =
      '<div class="state">' +
        "<h3>Projects unavailable</h3>" +
        "<p>" + esc(detail) + "</p>" +
        '<div class="btn-row" style="justify-content:center;margin-top:1.25rem">' +
          '<a class="btn btn--primary btn--sm" href="' + PROFILE_URL +
            '" target="_blank" rel="noopener noreferrer">View projects on GitHub</a>' +
        "</div>" +
      "</div>";
    if (statusEl) statusEl.textContent = "Projects could not be loaded.";
  }

  /* ======================================================================
     Boot — snapshot first, then live refresh
     ====================================================================== */
  var liveFailure = null;

  var livePromise = loadLive()
    .then(function (repos) {
      renderAll(repos, "live", null);
      return true;
    })
    .catch(function (err) {
      liveFailure = err && err.message ? err.message : "unavailable";
      return false;
    });

  loadSnapshot()
    .then(function (payload) {
      // Only paint the snapshot if the live query has not already won.
      if (state.source !== "live") {
        renderAll(payload.repos, "snapshot", payload.generatedAt);
      }
    })
    .catch(function () {
      // No snapshot — depend entirely on the live query.
      livePromise.then(function (ok) {
        if (!ok && !state.rendered) renderError(liveFailure);
      });
    });

  // Safety net: if nothing at all has rendered after 12s, show the fallback.
  setTimeout(function () {
    if (!state.rendered) renderError(liveFailure);
  }, 12000);
})();
